server:
  port: 83

spring:
  application:
    name: soup-config
  cloud:
    config:      server:        git:          uri: https://github.com/acesfullmike/konfig.git
          username: acesfullmike
          password: ${git.pwd}

eureka:
  instance:    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:80/eureka

info:
  who: Kevin Yu
  where: Guangzhou
  when: 2010